# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kustome < Formula
  desc "This tool can be used to initalize a kustomize.yaml for kustomize"
  homepage "https://github.com/steffakasid/kusto-me"
  version "0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/kusto-me/releases/download/0.6/kustome_0.6_Darwin_x86_64.tar.gz"
      sha256 "4dcd142dc2cf9fd63873d3a2f3d048141263284506d8b099f7036b3a1b37202b"

      def install
        bin.install "kustome"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/kusto-me/releases/download/0.6/kustome_0.6_Darwin_arm64.tar.gz"
      sha256 "d3d38d6ba73cebd0f622d0b6b93cd79a241e576ec1335370d9593d842da672b6"

      def install
        bin.install "kustome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/kusto-me/releases/download/0.6/kustome_0.6_Linux_arm64.tar.gz"
      sha256 "4f5d3187a9e257e93f5803835f5562e66a6b8c6062ae8b2b66fb92b5e47403cc"

      def install
        bin.install "kustome"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/kusto-me/releases/download/0.6/kustome_0.6_Linux_x86_64.tar.gz"
      sha256 "10e27b9b3d80c585c42cb8a0684d230151552b75cd3ddafd4524ed30d544b44d"

      def install
        bin.install "kustome"
      end
    end
  end
end
