# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kustome < Formula
  desc "This tool can be used to initalize a kustomize.yaml for kustomize"
  homepage "https://github.com/steffakasid/kusto-me"
  version "0.14"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/kusto-me/releases/download/v0.14/kustome_0.14_darwin_amd64.tar.gz"
      sha256 "046fb335a40870604d00c0967f2f71bcdec649762b0e6aeb28f319cf3e2c3ed1"

      def install
        bin.install "kustome"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/kusto-me/releases/download/v0.14/kustome_0.14_darwin_arm64.tar.gz"
      sha256 "ff99d056262fb7def5d82b2a815653c9c7e36624b780fb793136e05d045e4130"

      def install
        bin.install "kustome"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/kusto-me/releases/download/v0.14/kustome_0.14_linux_amd64.tar.gz"
        sha256 "2980e273fb12563be1863678f5a4be0d3da9844026f50bbcff5d44ec11dda701"

        def install
          bin.install "kustome"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/kusto-me/releases/download/v0.14/kustome_0.14_linux_arm64.tar.gz"
        sha256 "4d4486c238391c505517eda9726b575aefa5042b98225ba1d29a31d5f11a3381"

        def install
          bin.install "kustome"
        end
      end
    end
  end
end
